### ISSUE TITLE
EN-004-kp5aAUiZevI.srt (Review)

### ISSUE THREAD

**Issue by dnomak** [dnomak/youtube#4]
@hkan şu dosyayı tekrar review edebilirmisin :) https://github.com/dnomak/youtube/blob/master/srt/004-kp5aAUiZevI/EN-004-kp5aAUiZevI.srt

**Comment by hkan** [comment]
Gözüme çarpan bir sorun yok. Kullanılabilir durumda bence. 👍

**Comment by dnomak** [comment]
@hkan tamamdır süper :) @BYK abi sende bir göz atabilirsen süper olur :)

**Comment by tunix** [comment]
@dnomak PR olarak açsan daha iyi olur. 1-2 düzeltme olabilir gibi.

**Comment by dnomak** [comment]
@tunix mevcut repo üzerinden bir göz atar mısın müsait olunca varsa düzeltme alalım yoksa kapatıyorum :)

**Comment by tunix** [comment]
@dnomak kapat şimdilik o zaman :) enerjiyi diğerlerine harcarız.

**Comment by dnomak** [comment]
tamamdır :)
